# Generated by Django 5.2.7 on 2025-11-18 23:55

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$')])),
                ('nome_titular', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('\n    ^(?!\\s)                                                             # Não pode começar com espaço\n    [A-ZÀ-ÂÈ-ÊÌ-ÎÒ-ÔÙ-Û][a-zà-ãç-êì-îò-õù-û]+                           # Um prenome\n    ((\\ (da|das|do|dos))?\\ [A-ZÀ-ÂÈ-ÊÌ-ÎÒ-ÔÙ-Û][a-zà-ãç-êì-îò-õù-û]+)+  # Espaço mais sobrenome, com conjução opcional, 1+ vezes\n    (?<!\\s)$                                                            # Não pode terminar com espaço\n    ', 64))])),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(re.compile('\n        ^(?!\\s)     # Não pode começar com espaço\n        \\S+         # Palavra com qualquer char não espaço\n        (\\ \\S+)*    # Um espaço seguido de uma palavra com qualquer char não espaço, 0+ vezes\n        (?<!\\s)$    # Não pode terminar com espaço\n        ', 64))])),
                ('endereco', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_ifood.estabelecimento')),
                ('ofertas', models.ManyToManyField(blank=True, to='mini_ifood.oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(re.compile('\n    ^(?!\\s)                                                             # Não pode começar com espaço\n    [A-ZÀ-ÂÈ-ÊÌ-ÎÒ-ÔÙ-Û][a-zà-ãç-êì-îò-õù-û]+                           # Um prenome\n    ((\\ (da|das|do|dos))?\\ [A-ZÀ-ÂÈ-ÊÌ-ÎÒ-ÔÙ-Û][a-zà-ãç-êì-îò-õù-û]+)+  # Espaço mais sobrenome, com conjução opcional, 1+ vezes\n    (?<!\\s)$                                                            # Não pode terminar com espaço\n    ', 64))])),
                ('telefone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(re.compile('\n    ^([14689][1-9]|2[12478]|3[1234578]|5[1345]|7[134579])   # Possíveis DDDs do Brasil\n    9[0-9]{8}$                                              # Um 9 seguido de 8 digitos\n    ', 64))])),
                ('endereco', models.CharField(max_length=100)),
                ('carrinho', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mini_ifood.carrinho')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('formas_pagamento', models.ManyToManyField(blank=True, to='mini_ifood.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Pedido Recebido'), ('PR', 'Pedido em Preparo'), ('DL', 'À Caminho'), ('EN', 'Entregue')], default='RE', max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mini_ifood.cliente')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mini_ifood.estabelecimento')),
                ('ofertas', models.ManyToManyField(to='mini_ifood.oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ingredientes', models.TextField()),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_ifood.estabelecimento')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='prato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_ifood.prato'),
        ),
    ]
