---
config:
  theme: dark
---
erDiagram
  User["django.contrib.auth.models.User"] {
  }

  Cliente {
    int id_cliente
    string nome
    string telefone
  }

  Forma_Pagamento["Forma Pagamento"]  {
    int id_cartao
    string numero_cartao
    string nome_titular
    date vencimento
    string cvv
  }

  Estabelecimento {
    int id_estabelecimento
    string cnpj
    string razao_social
    string nome_fantasia
    string telefone
  }

  Endereco["Endereço"] {
    int id_endereco
    string cep
    int numero
    string rua
    string complemento
    string bairro
    string cidade
    string estado
  }

  Prato {
    int id_prato
    string nome
    text ingredientes
  }

  Pedido {
    int id_pedido
    enum status
  }

  Oferta {
    int id_oferta
    date data
    decimal valor
    int quantidade
  }

  Carrinho {
    int id_carrinho
  }

  User ||--o| Cliente : "do tipo"
  User ||--o| Estabelecimento : "do tipo"
  Cliente }|--o{ Forma_Pagamento : cadastra
  Estabelecimento |o--|| Endereco : "localizado em"
  Cliente }|--|{ Endereco : "recebe em"
  Oferta }o--|| Prato : oferta
  Pedido }o--|{ Oferta : "contém"
  Carrinho }o--o{ Oferta : "contém"
  Cliente ||--|| Carrinho : possui
  Cliente ||--o{ Pedido : realiza
  Estabelecimento ||--o{ Pedido : recebe
  Estabelecimento ||--|{ Prato : prepara